spring.application.name=todolist

# URL de conexão (ajuste o host, porta e nome_do_banco)
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB:todolist}
spring.datasource.username=${POSTGRES_USER:admin}
spring.datasource.password=${POSTGRES_PASSWORD:admin}

# Configurações do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
